name: MMCEssentials
main: net.moddedminecraft.mmcessentials.MMCEssentials
version: 0.6
author: Lee_lawd93
depend: [ProtocolLib]
commands:
   blockinfo:
    description: Main command for MMC Essentials.
    usage: /Blockfinfo
   mmce:
    description: Main command for MMC Essentials.
    usage: /MMCE help
permissions:
  mmcessentials.*:
    description: Provide all the permissions.
    children:
      mmcessentials.reload: true
      mmcessentials.hideplugins.bypass: true
    default: op
  mmcessentials.reload:
    description: Reload of the config.yml.
    default: op
  mmcessentials.hideplugins.bypass:
    description: Bypass the hide plugin's function to show the real information.
    default: op